### ISSUE TITLE
Failed to Run demo.py

### ISSUE THREAD

**Issue by luffy-yu** [facebookresearch/sam-3d-objects#15]
Thanks for the amazing work. 

Setting up the environment went well, but it failed to run `demo.py`.

Here is the log.

```
(sam3d-objects) n10288@N10288:~/Documents/Code/sam-3d-objects$ python demo.py 
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
Warp 1.10.0 initialized:
   CUDA Toolkit 12.8, Driver 13.0
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA GeForce RTX 5090" (31 GiB, sm_120, mempool enabled)
   Kernel cache:
     /home/n10288/.cache/warp/1.10.0
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/cuda/__init__.py:235: UserWarning: 
NVIDIA GeForce RTX 5090 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(
2025-11-20 14:22:12.511 | INFO     | sam3d_objects.pipeline.inference_pipeline:set_attention_backend:15 - GPU name is NVIDIA GeForce RTX 5090
2025-11-20 14:22:13.226 | INFO     | sam3d_objects.model.backbone.tdfy_dit.modules.sparse:__from_env:39 - [SPARSE] Backend: spconv, Attention: sdpa
2025-11-20 14:22:15.291 | INFO     | sam3d_objects.model.backbone.tdfy_dit.modules.attention:__from_env:30 - [ATTENTION] Using backend: sdpa
[SPARSE][CONV] spconv algo: auto
2025-11-20 14:22:15.463 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 14:22:15.463 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 14:22:15.482 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
model.pt: 100%|███████████████████████████████████████████████████████| 1.26G/1.26G [00:11<00:00, 112MB/s]
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/moge/model/v1.py:171: UserWarning: The following deprecated/invalid arguments are ignored: {'output_mask': True, 'split_head': True}
  warnings.warn(f"The following deprecated/invalid arguments are ignored: {deprecated_kwargs}")
2025-11-20 14:22:29.305 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 14:22:29.306 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:98 - self.device: cuda
2025-11-20 14:22:29.306 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:99 - CUDA_VISIBLE_DEVICES: None
2025-11-20 14:22:29.306 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:100 - Actually using GPU: 0
2025-11-20 14:22:29.306 | INFO     | sam3d_objects.pipeline.inference_pipeline:init_pose_decoder:295 - Using pose decoder: ScaleShiftInvariant
2025-11-20 14:22:29.306 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:131 - Loading model weights...
Traceback (most recent call last):
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/sam-3d-objects/sam3d_objects/model/backbone/tdfy_dit/models/mm_latent.py", line 17, in __init__
    self.input_layer = nn.Linear(in_channels, model_channels)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 112, in __init__
    self.reset_parameters()
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 118, in reset_parameters
    init.kaiming_uniform_(self.weight, a=math.sqrt(5))
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/nn/init.py", line 500, in kaiming_uniform_
    return torch.overrides.handle_torch_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/overrides.py", line 1717, in handle_torch_function
    result = mode.__torch_function__(public_api, types, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/utils/_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/nn/init.py", line 518, in kaiming_uniform_
    return tensor.uniform_(-bound, bound, generator=generator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/sam-3d-objects/sam3d_objects/pipeline/inference_pipeline_pointmap.py", line 99, in __init__
    super().__init__(*args, **kwargs)
  File "/home/n10288/Documents/Code/sam-3d-objects/sam3d_objects/pipeline/inference_pipeline.py", line 133, in __init__
    ss_generator = self.init_ss_generator(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/sam-3d-objects/sam3d_objects/pipeline/inference_pipeline.py", line 313, in init_ss_generator
    return self.instantiate_and_load_from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/sam-3d-objects/sam3d_objects/pipeline/inference_pipeline.py", line 269, in instantiate_and_load_from_pretrained
    model = instantiate(config)
            ^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 366, in instantiate_node
    cfg[key] = instantiate_node(
               ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'sam3d_objects.model.backbone.tdfy_dit.models.mm_latent.Latent':
RuntimeError('CUDA error: no kernel image is available for execution on the device\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n')
full_key: module.generator.backbone.reverse_fn.backbone.latent_mapping.6drotation_normalized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/n10288/Documents/Code/sam-3d-objects/demo.py", line 10, in <module>
    inference = Inference(config_path, compile=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/Documents/Code/sam-3d-objects/notebook/inference.py", line 92, in __init__
    self._pipeline: InferencePipelinePointMap = instantiate(config)
                                                ^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'sam3d_objects.pipeline.inference_pipeline_pointmap.InferencePipelinePointMap':
InstantiationException("Error in call to target 'sam3d_objects.model.backbone.tdfy_dit.models.mm_latent.Latent':\nRuntimeError('CUDA error: no kernel image is available for execution on the device\\nCUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1\\nCompile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\\n')\nfull_key: module.generator.backbone.reverse_fn.backbone.latent_mapping.6drotation_normalized")

```

PyTorch is installed and working.

```
>>> import torch
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
>>> print(torch.cuda.is_available())
True
```

**Comment by gleize** [comment]
Hi @luffy-yu,

It looks similar to https://github.com/facebookresearch/sam-3d-objects/issues/13. Could you try to make a small snippet to reproduce the error on your end ? It looks like `tensor.uniform_` is affected.
That would be very helpful to help us debug since we can't reproduce on our end.

**Comment by luffy-yu** [comment]
@gleize Thank you! I just solved it by building from source for some packages. This seems a common issue for RTX 50xx GPUs.

<img width="189" height="229" alt="Image" src="https://github.com/user-attachments/assets/fbc33575-141e-4134-bc04-605a2793c849" />

I will post the procedure and the entire environment later.

```
(sam3d-objects) n10288@N10288:~/Documents/Code/sam-3d-objects$ python demo.py 
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/torch/cuda/__init__.py:63: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
2025-11-20 17:29:58.313 | INFO     | sam3d_objects.pipeline.inference_pipeline:set_attention_backend:15 - GPU name is NVIDIA GeForce RTX 5090
2025-11-20 17:29:58.995 | INFO     | sam3d_objects.model.backbone.tdfy_dit.modules.sparse:__from_env:39 - [SPARSE] Backend: spconv, Attention: sdpa
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:47: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  _TORCH_CUSTOM_FWD = amp.custom_fwd(cast_inputs=torch.float16)
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:96: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:162: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:242: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:331: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:368: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:388: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/spconv/pytorch/functional.py:411: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  @_TORCH_CUSTOM_BWD
2025-11-20 17:30:00.856 | INFO     | sam3d_objects.model.backbone.tdfy_dit.modules.attention:__from_env:30 - [ATTENTION] Using backend: sdpa
[SPARSE][CONV] spconv algo: auto
2025-11-20 17:30:01.027 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 17:30:01.027 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 17:30:01.045 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
/home/n10288/miniconda3/envs/sam3d-objects/lib/python3.11/site-packages/moge/model/v1.py:171: UserWarning: The following deprecated/invalid arguments are ignored: {'output_mask': True, 'split_head': True}
  warnings.warn(f"The following deprecated/invalid arguments are ignored: {deprecated_kwargs}")
2025-11-20 17:30:03.406 | WARNING  | sam3d_objects.data.dataset.tdfy.preprocessor:__post_init__:51 - No rgb pointmap normalizer provided, using scale + shift 
2025-11-20 17:30:03.406 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:98 - self.device: cuda
2025-11-20 17:30:03.406 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:99 - CUDA_VISIBLE_DEVICES: None
2025-11-20 17:30:03.406 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:100 - Actually using GPU: 0
2025-11-20 17:30:03.407 | INFO     | sam3d_objects.pipeline.inference_pipeline:init_pose_decoder:295 - Using pose decoder: ScaleShiftInvariant
2025-11-20 17:30:03.407 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:131 - Loading model weights...
2025-11-20 17:30:03.524 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/ss_generator.ckpt
2025-11-20 17:30:08.009 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/slat_generator.ckpt
2025-11-20 17:30:10.041 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/ss_decoder.ckpt
2025-11-20 17:30:10.138 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/slat_decoder_gs.ckpt
2025-11-20 17:30:10.222 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/slat_decoder_gs_4.ckpt
2025-11-20 17:30:10.318 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/slat_decoder_mesh.ckpt
2025-11-20 17:30:10.426 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:31 - Loading DINO model: dinov2_vitl14_reg from facebookresearch/dinov2 (source: github)
Downloading: "https://github.com/facebookresearch/dinov2/zipball/main" to /home/n10288/.cache/torch/hub/main.zip
Downloading: "https://dl.fbaipublicfiles.com/dinov2/dinov2_vitl14/dinov2_vitl14_reg4_pretrain.pth" to /home/n10288/.cache/torch/hub/checkpoints/dinov2_vitl14_reg4_pretrain.pth
100%|█████████████████████████████████████████████████████████████████████████████████| 1.13G/1.13G [00:10<00:00, 115MB/s]
2025-11-20 17:30:23.911 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:44 - Loaded DINO model - type: <class 'dinov2.models.vision_transformer.DinoVisionTransformer'>, embed_dim: 1024, patch_size: (14, 14)
2025-11-20 17:30:23.913 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:31 - Loading DINO model: dinov2_vitl14_reg from facebookresearch/dinov2 (source: github)
2025-11-20 17:30:24.177 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:44 - Loaded DINO model - type: <class 'dinov2.models.vision_transformer.DinoVisionTransformer'>, embed_dim: 1024, patch_size: (14, 14)
2025-11-20 17:30:24.183 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/ss_generator.ckpt
2025-11-20 17:30:26.358 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:31 - Loading DINO model: dinov2_vitl14_reg from facebookresearch/dinov2 (source: github)
2025-11-20 17:30:26.654 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:44 - Loaded DINO model - type: <class 'dinov2.models.vision_transformer.DinoVisionTransformer'>, embed_dim: 1024, patch_size: (14, 14)
2025-11-20 17:30:26.656 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:31 - Loading DINO model: dinov2_vitl14_reg from facebookresearch/dinov2 (source: github)
2025-11-20 17:30:26.956 | INFO     | sam3d_objects.model.backbone.dit.embedder.dino:__init__:44 - Loaded DINO model - type: <class 'dinov2.models.vision_transformer.DinoVisionTransformer'>, embed_dim: 1024, patch_size: (14, 14)
2025-11-20 17:30:26.959 | INFO     | sam3d_objects.model.io:load_model_from_checkpoint:158 - Loading checkpoint from checkpoints/hf/slat_generator.ckpt
2025-11-20 17:30:28.449 | INFO     | sam3d_objects.pipeline.inference_pipeline:override_ss_generator_cfg_config:436 - ss_generator parameters: inference_steps=25, cfg_strength=7, cfg_interval=[0, 500], rescale_t=3, cfg_strength_pm=0.0
2025-11-20 17:30:28.449 | INFO     | sam3d_objects.pipeline.inference_pipeline:override_slat_generator_cfg_config:458 - slat_generator parameters: inference_steps=25, cfg_strength=1, cfg_interval=[0, 500], rescale_t=1
2025-11-20 17:30:28.449 | INFO     | sam3d_objects.pipeline.inference_pipeline:__init__:196 - Loading model weights completed!
2025-11-20 17:30:30.413 | INFO     | sam3d_objects.pipeline.inference_pipeline:sample_sparse_structure:662 - Sampling sparse structure: inference_steps=25, strength=7, interval=[0, 500], rescale_t=3, cfg_strength_pm=0.0
2025-11-20 17:30:30.414 | INFO     | sam3d_objects.pipeline.inference_pipeline:get_condition_input:631 - Running condition embedder ...
2025-11-20 17:30:30.480 | INFO     | sam3d_objects.pipeline.inference_pipeline:get_condition_input:635 - Condition embedder finishes!
2025-11-20 17:30:33.569 | INFO     | sam3d_objects.pipeline.inference_pipeline:sample_sparse_structure:712 - Downsampled coords from 26890 to 26337
2025-11-20 17:30:33.590 | INFO     | sam3d_objects.pipeline.inference_pipeline_pointmap:run:368 - Rescaling scale by 1 after downsampling
2025-11-20 17:30:33.590 | INFO     | sam3d_objects.pipeline.inference_pipeline:sample_slat:742 - Sampling sparse latent: inference_steps=25, strength=1, interval=[0, 500], rescale_t=1
2025-11-20 17:30:33.590 | INFO     | sam3d_objects.pipeline.inference_pipeline:get_condition_input:631 - Running condition embedder ...
2025-11-20 17:30:33.622 | INFO     | sam3d_objects.pipeline.inference_pipeline:get_condition_input:635 - Condition embedder finishes!
W1120 17:30:33.641000 211169 site-packages/torch/fx/_symbolic_trace.py:52] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.
2025-11-20 17:30:50.401 | INFO     | sam3d_objects.pipeline.inference_pipeline:decode_slat:604 - Decoding sparse latent...
2025-11-20 17:30:58.936 | INFO     | sam3d_objects.pipeline.inference_pipeline:postprocess_slat_output:538 - Postprocessing mesh with option with_mesh_postprocess False, with_texture_baking False...
2025-11-20 17:30:58.946 | INFO     | sam3d_objects.pipeline.inference_pipeline_pointmap:run:416 - Finished!
Your reconstruction has been saved to splat.ply

```

**Comment by yixuanhuang98** [comment]
I’m also using RTX 5090 GPUs and encountering the same issue. My GPU is running CUDA 12.9.

@luffy-yu, could you provide more details about which packages you built from source to successfully run demo.py on RTX 50-series GPUs? Thanks!

**Comment by luffy-yu** [comment]
# Build on Ubuntu 24.04.3 w/ RTX 5090

> Last updated @ Nov 21, 2025

### The following procedure is verified multiple times.

## Version
| Package | Repository | Version/Commit |
|---------|-----------|----------------|
| sam-3d-objects | [facebookresearch/sam-3d-objects](https://github.com/facebookresearch/sam-3d-objects.git) | 0e3d254f70c388efd10d6deae3f12a1344eb1957 |
| pytorch3d | [facebookresearch/pytorch3d](https://github.com/facebookresearch/pytorch3d) | V0.7.8 |
| kaolin | [NVIDIAGameWorks/kaolin](https://github.com/NVIDIAGameWorks/kaolin.git) | v0.18.0 |

- Clone them first and be aware of the **submodules**. 

## Build

- Download [sam3d-objects-single.yml](https://github.com/user-attachments/files/23684700/sam3d-objects-single.yml)

```
# Create environment
conda create -n sam3d-objects python=3.11

conda activate sam3d-objects

# Install torch
pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128

# Update dependency
conda env update -f sam3d-objects-single.yml

# Refresh (This is necessary.)
conda deactivate
conda activate sam3d-objects

# Build pytorch3d
python setup.py install

# Build kaolin
pip install -e . --no-build-isolation

# Run demo.py
python demo.py

## GOOD LUCK ^_^
```

## Full Dependencies

- Please refer to the `sam3d-objects.yml` and `requirements.txt`

- [sam3d-objects.yml](https://github.com/user-attachments/files/23684670/sam3d-objects.yml)
- [requirements.txt](https://github.com/user-attachments/files/23684669/requirements.txt)


> These two files are generated using my pypi package [conda-env-export](https://pypi.org/project/conda-env-export/) via command `conda-env-export --pip-all --conda-all --separate`.

**Comment by luffy-yu** [comment]
> Hi [@luffy-yu](https://github.com/luffy-yu),
> 
> It looks similar to [#13](https://github.com/facebookresearch/sam-3d-objects/issues/13). Could you try to make a small snippet to reproduce the error on your end ? It looks like `tensor.uniform_` is affected. That would be very helpful to help us debug since we can't reproduce on our end.

@gleize 

I solved it. You may refer to my above reply. I use a different version of PyTorch (2.9.0+cu128).

**Comment by luffy-yu** [comment]
> I’m also using RTX 5090 GPUs and encountering the same issue. My GPU is running CUDA 12.9.
> 
> [@luffy-yu](https://github.com/luffy-yu), could you provide more details about which packages you built from source to successfully run demo.py on RTX 50-series GPUs? Thanks!

@yixuanhuang98 Sure. See my above reply. You are welcome!

**Comment by gleize** [comment]
That's amazing @luffy-yu. Thanks a lot for solving it and sharing the solution.

**Comment by luffy-yu** [comment]
> That's amazing [@luffy-yu](https://github.com/luffy-yu). Thanks a lot for solving it and sharing the solution.

You are welcome. My pleasure.😁

**Comment by QuanNguyen94** [comment]
hi @luffy-yu @gleize , could I know how you guys can run the demo.py and export the model with texture ? I run but only get the model shape non-texture. Thanks

<img width="1427" height="795" alt="Image" src="https://github.com/user-attachments/assets/9c4cb836-10fe-46d7-8998-0a3490b472c1" />

**Comment by luffy-yu** [comment]
> hi [@luffy-yu](https://github.com/luffy-yu) [@gleize](https://github.com/gleize) , could I know how you guys can run the demo.py and export the model with texture ? I run but only get the model shape non-texture. Thanks
> 
> <img alt="Image" width="1427" height="795" src="https://private-user-images.githubusercontent.com/15965347/517182982-9c4cb836-10fe-46d7-8998-0a3490b472c1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2OTQzMzYsIm5iZiI6MTc2MzY5NDAzNiwicGF0aCI6Ii8xNTk2NTM0Ny81MTcxODI5ODItOWM0Y2I4MzYtMTBmZS00NmQ3LTg5OTgtMGEzNDkwYjQ3MmMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIxVDAzMDAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmOWM3ZGIwZmYzMjk4YzA0Y2E5MGIyMjc0MjY5YTA4Y2ZjMWMwNzQxOTUyZWU4NzdmZWZiMjJkMDcxMWYxMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RYMDtMQMW15c85EUJMOLCKzBoYCG-Wu5aFQpiQw7nss">

Hi @QuanNguyen94, I didn't modify the code. The default output is a Gaussian Splat, so I am using this [3DGS Render Blender Addon by KIRI Engine](https://github.com/Kiri-Innovation/3dgs-render-blender-addon).

**Comment by QuanNguyen94** [comment]
@luffy-yu  I see, I can get it with texture now. Thank you ~

**Comment by luffy-yu** [comment]
> [@luffy-yu](https://github.com/luffy-yu) I see, I can get it with texture now. Thank you ~

You are welcome. Were you trying to export as a mesh?

**Comment by QuanNguyen94** [comment]
yes

> > [@luffy-yu](https://github.com/luffy-yu) I see, I can get it with texture now. Thank you ~
> 
> You are welcome. Were you trying to export as a mesh?

**Comment by luffy-yu** [comment]
> yes
> 
> > > [@luffy-yu](https://github.com/luffy-yu) I see, I can get it with texture now. Thank you ~
> > 
> > 
> > You are welcome. Were you trying to export as a mesh?

Could you share your solution? I need to do that too. Thank you!

**Comment by QuanNguyen94** [comment]
sure u can add this line 
<img width="667" height="344" alt="Image" src="https://github.com/user-attachments/assets/608ee47f-4edb-45e4-8ed7-e6cd756a9f9c" />

**Comment by luffy-yu** [comment]
> sure u can add this line <img alt="Image" width="667" height="344" src="https://private-user-images.githubusercontent.com/15965347/517190194-608ee47f-4edb-45e4-8ed7-e6cd756a9f9c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM2OTU3OTIsIm5iZiI6MTc2MzY5NTQ5MiwicGF0aCI6Ii8xNTk2NTM0Ny81MTcxOTAxOTQtNjA4ZWU0N2YtNGVkYi00NWU0LThlZDctZTZjZDc1NmE5ZjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTIxVDAzMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTY3ZDBhZDNkM2I3Yzk2MjYwMzU0Y2UxZGJmYWFkOWNlZjJhYWE5ZDlkZjY5MDg3MzAwZGY0NGM1MjNiNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.35Zkffb7vy6U6Wtr51IxIamRLBMlWFl0njNkjF0jvmE">

I see. Thank you!

**Comment by gleize** [comment]
@QuanNguyen94 @luffy-yu
Regarding exporting the mesh, you can also have a look at https://github.com/facebookresearch/sam-3d-objects/issues/12#issuecomment-3560851396 regarding how to enable baking for better textures.

**Comment by luffy-yu** [comment]
> # Build on Ubuntu 24.04.3 w/ RTX 5090
> > Last updated @ Nov 21, 2025
> 
> ### The following procedure is verified multiple times.
> ## Version
> Package	Repository	Version/Commit
> sam-3d-objects	[facebookresearch/sam-3d-objects](https://github.com/facebookresearch/sam-3d-objects.git)	[0e3d254](https://github.com/facebookresearch/sam-3d-objects/commit/0e3d254f70c388efd10d6deae3f12a1344eb1957)
> pytorch3d	[facebookresearch/pytorch3d](https://github.com/facebookresearch/pytorch3d)	V0.7.8
> kaolin	[NVIDIAGameWorks/kaolin](https://github.com/NVIDIAGameWorks/kaolin.git)	v0.18.0
> * Clone them first and be aware of the **submodules**.
> 
> ## Build
> * Download [sam3d-objects-single.yml](https://github.com/user-attachments/files/23684700/sam3d-objects-single.yml)
> 
> ```
> # Create environment
> conda create -n sam3d-objects python=3.11
> 
> conda activate sam3d-objects
> 
> # Install torch
> pip install torch==2.8.0 torchvision==0.23.0 torchaudio==2.8.0 --index-url https://download.pytorch.org/whl/cu128
> 
> # Update dependency
> conda env update -f sam3d-objects-single.yml
> 
> # Refresh (This is necessary.)
> conda deactivate
> conda activate sam3d-objects
> 
> # Build pytorch3d
> python setup.py install
> 
> # Build kaolin
> pip install -e . --no-build-isolation
> 
> # Run demo.py
> python demo.py
> 
> ## GOOD LUCK ^_^
> ```
> 
> ## Full Dependencies
> * Please refer to the `sam3d-objects.yml` and `requirements.txt`
> * [sam3d-objects.yml](https://github.com/user-attachments/files/23684670/sam3d-objects.yml)
> * [requirements.txt](https://github.com/user-attachments/files/23684669/requirements.txt)
> 
> > These two files are generated using my pypi package [conda-env-export](https://pypi.org/project/conda-env-export/) via command `conda-env-export --pip-all --conda-all --separate`.

@gleize I just updated the installation process after testing multiple times. It works well now.

**Comment by luffy-yu** [comment]
I also post my solution on a gist, [Build SAM3D Objects on Ubuntu 24.04.3 w/ RTX 5090](https://gist.github.com/luffy-yu/3c9708aaf446d3640ef843c927ad9952).
