### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by shaonvpiaoyaodesilian** [facebookresearch/sam-3d-objects#68]
I seem to have set it up this way without success. I'm running demo_3db_mesh_alignment. Are there any other solutions? Thank you. I have already set the parameters in ppipeline.yaml to downsample_ss_dist: 8 and compile_model: true.
output = inference._pipeline.run(
  inference.merge_mask_to_rgba(image, mask),
  None,
  seed=10,decode_formats=["gaussian"]  # skip mesh decoding to save memory
)
still：
Error: At "Decoding sparse latent..."
Omitted content...
ret["gaussian"] = self.models["slat_decoder_gs"](slat)
Omitting...
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.15 GiB. GPU 0 has a total capacity of 23.64 GiB of which 3.10 GiB is free.

**Comment by gabrielklein** [comment]
I think the minimum is 32GiB. Personally I have 2x3090 in two different eGpu and it works.

**Comment by shaonvpiaoyaodesilian** [comment]
> 我认为最低要求是32GiB。我个人在两个不同的eGPU里都装了2块3090显卡，运行正常。
I have 4x4090 GPU, and my idea is to run part of the decoder model on other GPUs for inference. I'm unsure which models to target, and the code is a bit messy.
Could you provide some suggestions?Greatly appreciated

**Comment by shaonvpiaoyaodesilian** [comment]
I have four 4090 GPUs. Currently, I've successfully loaded sub-models onto different models, successfully bypassing the single-GPU 32GB requirement.

`self.devices = {

'depth_model': torch.device('cuda:0'), # Early stage

'ss_generator': torch.device('cuda:0'),

'ss_decoder': torch.device('cuda:0'),

'ss_encoder': torch.device('cuda:0'),

'ss_condition_embedder': torch.device('cuda:0'),

'slat_generator': torch.device('cuda:1'), # Later stage

'slat_decoder_gs': torch.device('cuda:1'),

'slat_decoder_gs_4': torch.device('cuda:1'),
` 'slat_decoder_mesh': torch.device('cuda:1'), 
'slat_condition_embedder': torch.device('cuda:1') 
}
